---
name: chatqu
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.0
  cloud_firestore: ^4.0.3
  firebase_auth: ^4.0.2
  firebase_storage: ^11.0.3
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  image_picker: ^0.8.6
  flutter_image_compress: ^1.1.3
  path_provider: ^2.0.11
  path: ^1.8.1
  shared_preferences: ^2.0.15
  sqflite: ^2.0.0+3
  intl: ^0.17.0
  chat_gpt_flutter: ^1.0.6
  firebase_crashlytics: ^3.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/images/
